#!/bin/bash 
# This deploy hook gets executed after dependencies are resolved and the 
# build hook has beenn run but before the application has been started back
# up again. This script gets executed directly, so it could be python, php,
# ruby, etc.

echo "---> ACTION HOOK: deploy <---"

source "$OPENSHIFT_HOMEDIR"python/virtenv/venv/bin/activate

echo "Executing:--> python $OPENSHIFT_REPO_DIR/manage.py syncdb --noinput"
python "$OPENSHIFT_REPO_DIR"/manage.py syncdb --noinput 

echo "Executing:--> python $OPENSHIFT_REPO_DIR/manage.py collectstatic --noinput"
python "$OPENSHIFT_REPO_DIR"/manage.py collectstatic --noinput

#export OPENSHIFT_PYTHON_WSGI_APPLICATION="$OPENSHIFT_REPO_DIR"geartest4/wsgi.py

#echo "@@@@@@@@@@@@@@@@@@@@@@@@@here is the OPENSHIFT_PYTHON_WSGI_APPLICATION path"
#echo "@@@@@--> $OPENSHIFT_PYTHON_WSGI_APPLICATION"


