#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available. Otherwise it will execute while your\napplication is stopped
# before the deploy step. This script gets executed directly, so it
# could be python, php, ruby, etc.
# Activate VirtualEnv in order to use the correct libraries

echo "--> ACTION HOOK: pre_build <---"

#export OPENSHIFT_PYTHON_WSGI_APPLICATION="$OPENSHIFT_REPO_DIR"geartest4/wsgi.py

#echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@here is the OPENSHIFT_PYTHON_WSGI_APPLICATION path"
#echo "@@@@@--> $OPENSHIFT_PYTHON_WSGI_APPLICATION"